### PR TITLE
create overloads for CreateLog and SubmitLog to accept the LogLevel enum

### PR DESCRIPTION
**Pull request by xbelt**
Same as previous pull request. Changed the syntax and removed unnecessary code. Had to put the code into a new branch so all changes were reflected in a single commit

### CODE REVIEW

**Comment by niemyjski** [comment]
@xbelt Looks good. 

@ejsmith I almost wonder if we should be putting a default log level on this overload but I guess it would make things inconsistent.

**Comment by niemyjski** [comment]
@xbelt Thanks for your contribution!

**Comment by xbelt** [comment]
@niemyjski I would refrain from putting a default log level on this overload. As you said it could make things inconsistent since there is already an overload of SubmitLog() which only requires a source and a message.

**Comment by niemyjski** [comment]
I agree

**Pull request merged**
