### PR TITLE
Added SubmitLog and CreateLog without source parameter

### PR DESCRIPTION
**Pull request by ahmettaha**

### CODE REVIEW

**Comment by niemyjski** [comment]
Thank you for your pull request, can you please sign our CLA (https://www.clahub.com/agreements/exceptionless/Exceptionless) and also fix the bracket casing to match the rest of the code (installing this addon should help a lot https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58)

**Comment by ahmettaha** [comment]
I can not sign it. it says something went wrong.



.

**Comment by niemyjski** [comment]
Can you please send a quick email to team@exceptionless.com with your info as record and I'll see what's going on with our cla solution :(.

Other than that, the pull request looks good except for the bracket formatting. I'm prepping a release right now, so I can get this change out shortly once brackets are fixed.

**Comment by ahmettaha** [comment]
I have added the brackets. Do I need to do anything else?

**Comment by niemyjski** [comment]
I've added a new CLA check, can you please sign the new cla :).

**Comment by niemyjski** [comment]
I think you just need to click here: https://cla-assistant.io/exceptionless/Exceptionless.Net?pullRequest=79

**Comment by niemyjski** [comment]
Awesome Thank you!!

**Pull request merged**
